title: Nadia (Nadezhda) Pozdnyakova
description: Assistant Professor at New Economic School
logo: photo_website.jpg
theme: jekyll-theme-minimal

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

navigation:
  - name: Home
    link: ./home.html
  - name: Research
    link: ./research.html
  - name: Teaching
    link: ./teaching.html
 # - name: CV
 #   link: ./cv.html
